server:
  port: 8761

spring:
  application:
    name: discovery-svc
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: discovery-svc
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
